language: php 
php: 
 - 5.3
 - 5.4

env:
 - TESTDB=MYSQL CORE_RELEASE=3.0
 - TESTDB=MYSQL CORE_RELEASE=master
 - TESTDB=PGSQL CORE_RELEASE=master

matrix:
  exclude:
    - php: 5.4
      env: TESTDB=PGSQL CORE_RELEASE=master
    - php: 5.4
      env: TESTDB=MYSQL CORE_RELEASE=3.0

before_script:
 - pear -q install --onlyreqdeps pear/PHP_CodeSniffer
 - phpenv rehash
 - ./tests/travis/before_script ~/builds/ss 
 - cd ~/builds/ss

script: 
 - phpunit newsletter/tests/
 - phpcs --encoding=utf-8 --tab-width=4 --standard=newsletter/tests/phpcs --ignore="_old/*,lang/*" -np newsletter